### ISSUE TITLE
About Us - Development Group A + B - AS IS ON 7/15/2023@Abhay (Dev Team) @Kenneth W. (Dev) @Sasi (Dev)

### ISSUE THREAD

**Issue by RinSoftwareDeveloper** [MEGA-Hackathon/china.megahack.tech#5]
@Abdev1205 
@kennlw 
@AdamBures 

Team A has been added of July 15th

Due date: 
7/16/2023

If needed, I can assign more of Group A developers into group B to assist in hopes of completing the deadline.

The goal of the deadline is to have both the English and Chinese sites completed before the Due Date.

Design:
https://www.figma.com/file/GNFBOM8UbfLvDo5t4CNnKN/MEGA-China-Web-Design?type=design&node-id=0-1&mode=design&t=OHc09EKDd4uLV0x9-0

**Comment by AdamBures** [comment]
I am Sasi so for further inquiries use @AdamBures

**Comment by RinSoftwareDeveloper** [comment]
> I am Sasi so for further inquiries use @AdamBures

ok thank you, i have assigned you this task

**Comment by RinSoftwareDeveloper** [comment]
@CenturionConfidence 
@KaiPereira 
@hisham (don't have you github)

moved you guys to group B to help out there

@labhk finish polishing and then i will redelegate you as well
